{% set name = "runner" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/runner-suite/runner-conda/-/archive/{{ version }}/runner-conda-{{ version }}.tar.gz
  sha256: 69965dcfde64530b7a75708c25e6243363e0a5745e66ac458a1e7086592538a2
  patches:
    - mpi.patch  # [mpi != 'nompi']

build:
  number: 3
  skip: ture  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - {{ mpi }}-mpifort  # [mpi != 'nompi']
  host:
    - libblas
    - liblapack
    - {{ mpi }}  # [mpi != 'nompi']
  run:
    - {{ mpi }}  # [mpi != 'nompi']

test:
  commands:
    - RuNNer.serial.x

about:
  home: https://www.uni-goettingen.de/de/560580.html
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'RuNNer - a Neural Network code for high-dimensional systems'
  description: |
    In order to develop Neural Network potential-energy surfaces for a 
    variety of system, we have developed our in-house NN code for 
    high-dimensional systems called RuNNer, which was the first 
    implementation of high-dimensional NN potentials. Much of the 
    methodology has been originally developed with this code.
  doc_url: https://www.uni-goettingen.de/de/560580.html
  dev_url: https://gitlab.com/TheochemGoettingen/runner-wfas/

extra:
  recipe-maintainers:
    - lxknll
    - jan-janssen
